version: "3.8"

services:
  nats:
    restart: unless-stopped
    image: nats:latest
    command: --jetstream -m 8222
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      - network

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./api/docker/build.Dockerfile
    ports:
      - 8080:80
    environment:
      PORT: 80
      NATS_URL: "nats://nats:4222"
    depends_on:
      - nats
    networks:
      - network

  simulator:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./simulator/docker/build.Dockerfile
    environment:
      NATS_URL: "nats://nats:4222"
    depends_on:
      - nats
    networks:
      - network

networks:
  network:
