// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package mock_config is a generated GoMock package.
package mock_config

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConfigInterface is a mock of ConfigInterface interface.
type MockConfigInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConfigInterfaceMockRecorder
}

// MockConfigInterfaceMockRecorder is the mock recorder for MockConfigInterface.
type MockConfigInterfaceMockRecorder struct {
	mock *MockConfigInterface
}

// NewMockConfigInterface creates a new mock instance.
func NewMockConfigInterface(ctrl *gomock.Controller) *MockConfigInterface {
	mock := &MockConfigInterface{ctrl: ctrl}
	mock.recorder = &MockConfigInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigInterface) EXPECT() *MockConfigInterfaceMockRecorder {
	return m.recorder
}

// GetListeningPort mocks base method.
func (m *MockConfigInterface) GetListeningPort() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListeningPort")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetListeningPort indicates an expected call of GetListeningPort.
func (mr *MockConfigInterfaceMockRecorder) GetListeningPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListeningPort", reflect.TypeOf((*MockConfigInterface)(nil).GetListeningPort))
}

// GetNatsUrl mocks base method.
func (m *MockConfigInterface) GetNatsUrl() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNatsUrl")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNatsUrl indicates an expected call of GetNatsUrl.
func (mr *MockConfigInterfaceMockRecorder) GetNatsUrl() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNatsUrl", reflect.TypeOf((*MockConfigInterface)(nil).GetNatsUrl))
}
